import { beforeEach, it, expect, vi } from "vitest";
import { render, screen, fireEvent, act } from "@testing-library/react";
import ArchitectureAiPanel from "../src/components/architecture/ArchitectureAiPanel";
import { askArchitecture } from "../src/api/architecture";
import { graphFixture } from "./fixtures/architectureGraph";
import { relationshipId } from "../src/components/architecture/architectureGraphAdapter";
vi.mock("../src/api/architecture", () => ({ askArchitecture: vi.fn() }));
const data = graphFixture();
const source = { id: "S1", chunkId: 44, path: data.components[0].path, startLine: 10, endLine: 35, symbol: "Symbol0", language: "JAVA" };
const answer = { repositoryId: 12, indexCommitSha: data.indexCommitSha, answer: "The component depends on a service. [A1] [E1] [S1]", components: [{ ref: "A1", id: data.components[0].id, name: "Unit0", type: "CONTROLLER" }], relationships: [{ ref: "E1", ...data.relationships[0] }], sources: [source], grounded: true, warnings: ["Bounded evidence"] };
let callbacks;
function panel(extra = {}) { return render(<ArchitectureAiPanel data={data} {...callbacks} {...extra} />); }
function ask(text = "How does this work?") { fireEvent.change(screen.getByLabelText("Architecture question"), { target: { value: text } }); fireEvent.click(screen.getByRole("button", { name: "Ask architecture", exact: true })); }
async function answered() { await screen.findByRole("button", { name: "Go to citation A1" }); }
beforeEach(() => { callbacks = { onNavigate: vi.fn(), onHighlight: vi.fn(), onClearContext: vi.fn() }; askArchitecture.mockResolvedValue(answer); Object.defineProperty(navigator, "clipboard", { configurable: true, value: { writeText: vi.fn().mockResolvedValue() } }); });
it("AI panel renders with an accessible question field", () => { panel(); expect(screen.getByRole("region", { name: "AI Architecture Intelligence" })).not.toBeNull(); expect(screen.getByLabelText("Architecture question").maxLength).toBe(4000); });
it("selected backend node context is displayed", () => { panel({ selectedComponentId: "backend-0001" }); expect(screen.getByText("Unit1", { exact: true })).not.toBeNull(); });
it("clear context returns control to repository scope", () => { panel({ selectedComponentId: "backend-0001" }); fireEvent.click(screen.getByRole("button", { name: "Clear context" })); expect(callbacks.onClearContext).toHaveBeenCalled(); });
it("repository question omits selected ID and source metadata", async () => { panel(); ask(); await answered(); expect(askArchitecture.mock.calls[0][1]).toEqual({ question: "How does this work?", indexCommitSha: data.indexCommitSha }); });
it("selected request sends only ID question and snapshot", async () => { panel({ selectedComponentId: "backend-0001" }); ask(); await answered(); expect(askArchitecture.mock.calls[0][1]).toEqual({ question: "How does this work?", selectedComponentId: "backend-0001", indexCommitSha: data.indexCommitSha }); });
it.each([["Explain Component", "Explain the role of this component in the repository architecture."], ["Explain Connections", "Explain how this component interacts with its connected components."]])("%s is accessible and sends the prescribed question", async (label, question) => { panel({ selectedComponentId: "backend-0000" }); fireEvent.click(screen.getByRole("button", { name: label })); await answered(); expect(askArchitecture.mock.calls[0][1].question).toBe(question); });
it("blank question cannot submit", () => { panel(); expect(screen.getByRole("button", { name: "Ask architecture" }).disabled).toBe(true); ask("  "); expect(askArchitecture).not.toHaveBeenCalled(); });
it("loading has status and disables submit", () => { askArchitecture.mockReturnValue(new Promise(() => {})); panel(); ask(); expect(screen.getByRole("status").textContent).toContain("Analyzing repository architecture"); expect(screen.getByRole("button", { name: "Analyzing repository architecture..." }).disabled).toBe(true); });
it("same-tick double submission calls API once", () => { askArchitecture.mockReturnValue(new Promise(() => {})); panel(); ask(); fireEvent.submit(screen.getByLabelText("Architecture question").closest("form")); expect(askArchitecture).toHaveBeenCalledTimes(1); });
it("provider response rendered as text with validated source citation", async () => { panel(); ask(); await answered(); expect(screen.getByRole("button", { name: "Go to citation S1" })).not.toBeNull(); expect(screen.getByText(/The component depends/)).not.toBeNull(); });
it("source citation opens source copy foundation", async () => { panel(); ask(); await answered(); fireEvent.click(screen.getByRole("button", { name: "Go to citation S1" })); fireEvent.click(screen.getByRole("button", { name: `Copy source location ${source.path}:10-35` })); expect(navigator.clipboard.writeText).toHaveBeenCalledWith(`${source.path}:10-35`); });
it("component citation selects the actual graph node", async () => { panel(); ask(); await answered(); fireEvent.click(screen.getByRole("button", { name: "Go to citation A1" })); expect(callbacks.onNavigate).toHaveBeenCalledWith({ kind: "node", id: "backend-0000" }); });
it("relationship citation selects actual directed edge", async () => { panel(); ask(); await answered(); fireEvent.click(screen.getByRole("button", { name: "Go to citation E1" })); expect(callbacks.onNavigate).toHaveBeenCalledWith({ kind: "edge", id: relationshipId(data.relationships[0]) }); });
it("show in graph uses backend IDs only", async () => { panel(); ask(); await answered(); fireEvent.click(screen.getByRole("button", { name: "Show in graph" })); expect(callbacks.onHighlight).toHaveBeenLastCalledWith(["backend-0000"]); });
it("clear graph highlight is available", async () => { panel({ highlightedIds: ["backend-0000"] }); ask(); await answered(); fireEvent.click(screen.getByRole("button", { name: "Clear highlight" })); expect(callbacks.onHighlight).toHaveBeenLastCalledWith([]); });
it.each([[503,"temporarily unavailable"],[504,"timed out"],[429,"rate limit"],[500,"Unable to complete"],[400,"Check your question"],[409,"Reload architecture"],[404,"not accessible"]])("HTTP %i maps to a safe error", async (status, message) => { askArchitecture.mockRejectedValue({ response: { status, data: { message: "raw-secret-stack" } } }); panel(); ask(); expect((await screen.findByRole("alert")).textContent).toContain(message); expect(screen.queryByText(/raw-secret-stack/)).toBeNull(); });
it("insufficient evidence produces no invented citations", async () => { askArchitecture.mockResolvedValue({ ...answer, grounded: false, answer: "I don't have enough repository evidence to answer this reliably.", sources: [], components: [], relationships: [] }); panel(); ask(); expect(await screen.findByText("Insufficient repository evidence.")).not.toBeNull(); expect(screen.queryByRole("button", { name: "Go to citation A1" })).toBeNull(); });
it("no components disables architecture AI entirely", () => { panel({ data: graphFixture(0) }); expect(screen.getByText("Architecture analysis did not detect supported components for this repository.")).not.toBeNull(); expect(screen.queryByRole("textbox")).toBeNull(); expect(askArchitecture).not.toHaveBeenCalled(); });
it("graph warnings remain visible in AI context", () => { panel({ data: { ...data, warnings: ["limited"] } }); expect(screen.getByText(/Architecture scope is limited/)).not.toBeNull(); });
it("unmount aborts request and ignores later answer", async () => { let done; askArchitecture.mockReturnValue(new Promise(r => { done = r; })); const view = panel(); ask(); const signal = askArchitecture.mock.calls[0][2]; view.unmount(); await act(async () => done(answer)); expect(signal.aborted).toBe(true); });
it.each(["repository", "component", "snapshot"])("%s change aborts stale response", async kind => { let done; askArchitecture.mockReturnValue(new Promise(r => { done = r; })); const view = panel(); ask(); const signal = askArchitecture.mock.calls[0][2]; const props = kind === "repository" ? { data: { ...data, repositoryId: 13 } } : kind === "snapshot" ? { data: { ...data, indexCommitSha: "b".repeat(40) } } : { selectedComponentId: "backend-0001" }; view.rerender(<ArchitectureAiPanel data={data} {...callbacks} {...props} />); await act(async () => done(answer)); expect(signal.aborted).toBe(true); expect(screen.queryByRole("button", { name: "Go to citation A1" })).toBeNull(); });
it("cancel aborts request and permits a new question", async () => { let done; askArchitecture.mockReturnValueOnce(new Promise(r => { done = r; })); panel(); ask(); const signal = askArchitecture.mock.calls[0][2]; fireEvent.click(screen.getByRole("button", { name: "Cancel analysis" })); await act(async () => done(answer)); expect(signal.aborted).toBe(true); expect(screen.getByRole("button", { name: "Ask architecture" }).disabled).toBe(false); });
it("keyboard Ctrl+Enter submits", async () => { panel(); fireEvent.change(screen.getByLabelText("Architecture question"), { target: { value: "Explain" } }); fireEvent.keyDown(screen.getByLabelText("Architecture question"), { key: "Enter", ctrlKey: true }); await answered(); expect(askArchitecture).toHaveBeenCalledTimes(1); });
it("HTML is never executed or interpreted", async () => { askArchitecture.mockResolvedValue({ ...answer, answer: '<script>alert(1)</script><img src=x onerror=alert(1)> [A1]' }); const view = panel(); ask(); await answered(); expect(view.container.querySelectorAll("script,img")).toHaveLength(0); expect(screen.getByText(/<script>alert/)).not.toBeNull(); });
it("unknown response component cannot become graph node", async () => { askArchitecture.mockResolvedValue({ ...answer, components: [{ ref: "A999", id: "fake", name: "Fake" }], answer: "Untrusted [A999]" }); panel(); ask(); await screen.findByText(/Untrusted/); expect(screen.queryByRole("button", { name: "Go to citation A999" })).toBeNull(); expect(screen.queryByRole("button", { name: "Show in graph" })).toBeNull(); });
it("wrong snapshot response is rejected", async () => { askArchitecture.mockResolvedValue({ ...answer, indexCommitSha: "b".repeat(40) }); panel(); ask(); expect((await screen.findByRole("alert")).textContent).toContain("Reload architecture"); });
it("no answer is shown before a real response", () => { askArchitecture.mockReturnValue(new Promise(() => {})); panel(); ask(); expect(screen.queryByLabelText("Architecture answer")).toBeNull(); });
it.each(["Chat API key is not configured", "Embedding API key is not configured"])("missing provider configuration stays explicit: %s", async message => {
  askArchitecture.mockRejectedValue({ response: { status: 503, data: { message } } });
  panel(); ask();
  expect((await screen.findByRole("alert")).textContent).toBe("AI provider is not configured for this DevPilot instance.");
  expect(screen.queryByLabelText("Architecture answer")).toBeNull();
});
