import { beforeEach, it, expect, vi } from "vitest";
import { render, screen, fireEvent, waitFor } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import { graphFixture } from "./fixtures/architectureGraph";
const flow = vi.hoisted(() => ({ fitView: vi.fn(), setCenter: vi.fn() }));
vi.mock("@xyflow/react", async () => {
  const { useEffect } = await import("react");
  return {
    ReactFlowProvider: ({ children }) => children,
    ReactFlow: ({ nodes, edges, onInit, onNodeClick, onEdgeClick, nodeTypes, children }) => {
      useEffect(() => { onInit(flow); }, [onInit]);
      const Node = nodeTypes.architecture;
      return <div data-testid="canvas"><div>{nodes.map(n => <button key={n.id} aria-label={`Select ${n.ariaLabel}`} data-node-id={n.id} className={n.className} onClick={event => onNodeClick(event, n)}><Node data={n.data} /></button>)}</div><div>{edges.map(e => <button key={e.id} aria-label={`Edge ${e.ariaLabel}`} onClick={event => onEdgeClick(event, e)}>{e.label}</button>)}</div>{children}</div>;
    },
    Handle: () => null, Position: { Top: "top", Bottom: "bottom" }, Background: () => null, Controls: () => null, MiniMap: () => <p>Minimap</p>,
  };
});
vi.mock("../src/components/architecture/layoutRequest", () => ({ requestArchitectureLayout: vi.fn() }));
import { requestArchitectureLayout } from "../src/components/architecture/layoutRequest";
import ArchitectureGraph from "../src/components/architecture/ArchitectureGraph";
import { ArchitectureViews } from "../src/pages/ArchitecturePage";
function renderGraph(data = graphFixture()) { return render(<ArchitectureGraph data={data} />); }
function selectNode(name = "Unit0", type = "CONTROLLER") { fireEvent.click(screen.getByRole("button", { name: `Select ${name} · ${type}` })); }
beforeEach(() => {
  requestArchitectureLayout.mockImplementation((graph, done) => { done(graph.nodes.map((n, i) => ({ id: n.id, position: { x: i * 280, y: 10 } }))); return vi.fn(); });
  Object.defineProperty(navigator, "clipboard", { configurable: true, value: { writeText: vi.fn().mockResolvedValue() } });
  flow.fitView.mockClear(); flow.setCenter.mockClear();
});
it("Graph is default and Components fallback remains available", async () => { render(<MemoryRouter><ArchitectureViews data={graphFixture()} /></MemoryRouter>); expect(screen.getByRole("button", { name: "Graph" }).getAttribute("aria-pressed")).toBe("true"); await screen.findByTestId("canvas"); fireEvent.click(screen.getByRole("button", { name: "Components", exact: true })); expect(screen.getByRole("heading", { name: "Controllers" })).not.toBeNull(); expect(screen.queryByTestId("canvas")).toBeNull(); });
it("node click opens full source-backed details", () => { renderGraph(); selectNode(); const panel = screen.getByRole("complementary", { name: "Component detail" }); expect(panel.textContent).toContain("fixture.Unit0"); expect(panel.textContent).toContain("JAVA"); expect(panel.textContent).toContain("Lines 10–35"); expect(panel.textContent).toContain("Symbol0"); });
it("incoming/outgoing relationships and metadata appear", () => { renderGraph(); selectNode(); expect(screen.getByRole("heading", { name: "Incoming relationships" })).not.toBeNull(); expect(screen.getByRole("heading", { name: "Outgoing relationships" })).not.toBeNull(); expect(screen.getByText("GET /api/items")).not.toBeNull(); });
it("related node selection centers the exact backend node", () => { renderGraph(); selectNode(); fireEvent.click(screen.getByRole("button", { name: "Unit1", exact: true })); expect(screen.getByRole("complementary", { name: "Component detail" }).textContent).toContain("fixture.Unit1"); expect(flow.setCenter).toHaveBeenLastCalledWith(404, 56, expect.objectContaining({ zoom: .9 })); });
it("entity metadata is not inferred", () => { renderGraph(); selectNode("Unit3", "ENTITY"); expect(screen.getByText("items")).not.toBeNull(); expect(screen.getByText("Entity: Item")).not.toBeNull(); });
it("entry point metadata uses backend entryPoints", () => { renderGraph(graphFixture(10)); selectNode("Unit8", "ENTRY_POINT"); expect(screen.getByText("Detected entry point")).not.toBeNull(); });
it("source location click copies actual path and lines without fabricating URL", async () => { renderGraph(); selectNode(); fireEvent.click(screen.getByRole("button", { name: "Copy source location src/feature0/Unit0.java:10-35" })); expect(navigator.clipboard.writeText).toHaveBeenCalledWith("src/feature0/Unit0.java:10-35"); expect(await screen.findByText("Source location copied.")).not.toBeNull(); });
it("edge selection shows actual evidence", () => { renderGraph(); fireEvent.click(screen.getByRole("button", { name: "Edge Unit0 → DEPENDS_ON → Unit1" })); const panel = screen.getByRole("complementary", { name: "Relationship detail" }); expect(panel.textContent).toContain("Unit0 → Unit1"); expect(panel.textContent).toContain("Lines 14–15"); expect(panel.textContent).toContain("constructor"); });
it("missing evidence gets no fabricated source", () => { const data = graphFixture(2); delete data.relationships[0].evidence; renderGraph(data); fireEvent.click(screen.getByRole("button", { name: /Edge Unit0/ })); expect(screen.getByText("No source location was supplied.")).not.toBeNull(); });
it("search by component name selects and focuses node", () => { renderGraph(); fireEvent.change(screen.getByPlaceholderText("Search architecture..."), { target: { value: "unit2" } }); fireEvent.click(screen.getByRole("button", { name: /Unit2 REPOSITORY src/ })); expect(screen.getByRole("complementary", { name: "Component detail" }).textContent).toContain("fixture.Unit2"); expect(flow.setCenter).toHaveBeenCalled(); });
it.each(["feature1", "SERVICE", "fixture.Unit1", "Symbol1"])("local search matches %s", query => { renderGraph(); fireEvent.change(screen.getByLabelText("Search architecture"), { target: { value: query } }); const results = screen.getByRole("region", { name: "Architecture search results" }); expect(results.textContent).toContain("Unit1"); expect(results.textContent).not.toContain("Unit0"); });
it("type filter removes node and dangling edges", () => { renderGraph(); fireEvent.click(screen.getByText("Filters", { selector: "summary" })); fireEvent.click(screen.getByRole("checkbox", { name: "SERVICE", exact: true })); expect(screen.queryByRole("button", { name: "Select Unit1 · SERVICE" })).toBeNull(); expect(screen.queryByRole("button", { name: "Edge Unit0 → DEPENDS_ON → Unit1" })).toBeNull(); });
it("relationship filter preserves nodes", () => { renderGraph(); fireEvent.click(screen.getByText("Filters", { selector: "summary" })); fireEvent.click(screen.getByRole("checkbox", { name: "DEPENDS_ON", exact: true })); expect(screen.getByRole("button", { name: "Select Unit1 · SERVICE" })).not.toBeNull(); expect(screen.queryByRole("button", { name: /Edge Unit0 → DEPENDS_ON/ })).toBeNull(); });
it("reset clears filters search selection and fits", async () => { renderGraph(); selectNode(); fireEvent.change(screen.getByLabelText("Search architecture"), { target: { value: "Unit0" } }); fireEvent.click(screen.getByText("Filters", { selector: "summary" })); fireEvent.click(screen.getByRole("checkbox", { name: "SERVICE", exact: true })); fireEvent.click(screen.getByRole("button", { name: "Reset view" })); expect(screen.getByLabelText("Search architecture").value).toBe(""); expect(screen.queryByRole("complementary", { name: "Component detail" })).toBeNull(); expect(screen.getByRole("button", { name: "Select Unit1 · SERVICE" })).not.toBeNull(); await waitFor(() => expect(flow.fitView.mock.calls.length).toBeGreaterThan(1)); });
it("snapshot shows short and accessible full SHA", () => { renderGraph(); expect(screen.getByText("aaaaaaaaaa")).not.toBeNull(); expect(screen.getByRole("button", { name: "Copy snapshot SHA" }).title).toBe("a".repeat(40)); });
it("backend warnings stay visible", () => { renderGraph({ ...graphFixture(), warnings: ["Architecture graph was limited to 1000 components."] }); expect(screen.getByText("Architecture graph was limited to 1000 components.")).not.toBeNull(); });
it("empty graph does not mount canvas or invent components", () => { renderGraph(graphFixture(0)); expect(screen.getByRole("heading", { name: "No supported architecture components were detected for this repository." })).not.toBeNull(); expect(screen.queryByTestId("canvas")).toBeNull(); expect(requestArchitectureLayout).not.toHaveBeenCalled(); });
it("layout loading has a stable state", () => { requestArchitectureLayout.mockImplementation(() => vi.fn()); renderGraph(); expect(screen.getByText("Arranging architecture map…")).not.toBeNull(); });
it("layout error offers a readable fallback message", () => { requestArchitectureLayout.mockImplementation((_, __, fail) => { fail("Use Components view: layout unavailable."); return vi.fn(); }); renderGraph(); expect(screen.getByRole("alert").textContent).toContain("Use Components view"); });
it("unknown enum types render safely", () => { const data = graphFixture(2); data.components[0].type = "FUTURE_TYPE"; data.relationships[0].type = "FUTURE_EDGE"; renderGraph(data); expect(screen.getByRole("button", { name: "Select Unit0 · FUTURE_TYPE" })).not.toBeNull(); expect(screen.getByRole("button", { name: "Edge Unit0 → FUTURE_EDGE → Unit1" })).not.toBeNull(); });
it("close button and Escape close details and restore search focus", () => { renderGraph(); selectNode(); fireEvent.click(screen.getByRole("button", { name: "Close details" })); expect(screen.queryByRole("complementary", { name: "Component detail" })).toBeNull(); selectNode(); fireEvent.keyDown(screen.getByRole("complementary", { name: "Component detail" }), { key: "Escape" }); expect(screen.queryByRole("complementary", { name: "Component detail" })).toBeNull(); expect(document.activeElement).toBe(screen.getByLabelText("Search architecture")); });
it("controls and search have accessible names", () => { renderGraph(); expect(screen.getByRole("button", { name: "Fit View" })).not.toBeNull(); expect(screen.getByRole("button", { name: "Reset view" })).not.toBeNull(); expect(screen.getByLabelText("Search architecture")).not.toBeNull(); });
it("selection search and filters never recompute layout", () => { renderGraph(); selectNode(); fireEvent.change(screen.getByLabelText("Search architecture"), { target: { value: "Unit0" } }); fireEvent.click(screen.getByText("Filters", { selector: "summary" })); fireEvent.click(screen.getByRole("checkbox", { name: "SERVICE", exact: true })); expect(requestArchitectureLayout).toHaveBeenCalledTimes(1); });
it("large graph uses minimap and bounded search results", () => { renderGraph(graphFixture(1000)); expect(screen.getByText("Minimap")).not.toBeNull(); fireEvent.click(screen.getByRole("button", { name: "Browse components" })); const results = screen.getByRole("region", { name: "Architecture search results" }); expect(results.querySelectorAll("li")).toHaveLength(50); fireEvent.click(screen.getByRole("button", { name: "Show more components" })); expect(results.querySelectorAll("li")).toHaveLength(100); });
it("small graph has no minimap clutter", () => { renderGraph(); expect(screen.queryByText("Minimap")).toBeNull(); });
it("unmount terminates layout work", () => { const stop = vi.fn(); requestArchitectureLayout.mockReturnValue(stop); const view = renderGraph(); view.unmount(); expect(stop).toHaveBeenCalled(); });
it("answer navigation selects and centers the existing backend node", () => { render(<ArchitectureGraph data={graphFixture()} navigation={{ kind: "node", id: "backend-0001" }} />); expect(screen.getByRole("complementary", { name: "Component detail" }).textContent).toContain("fixture.Unit1"); expect(flow.setCenter).toHaveBeenLastCalledWith(404, 56, expect.objectContaining({ zoom: .9 })); });
it("answer navigation cannot create a node", () => { render(<ArchitectureGraph data={graphFixture()} navigation={{ kind: "node", id: "unknown" }} />); expect(screen.queryByRole("complementary", { name: "Component detail" })).toBeNull(); });
it("answer highlight marks only supplied existing nodes", () => { render(<ArchitectureGraph data={graphFixture()} highlightedIds={["backend-0000", "fake"]} />); expect(screen.getByRole("button", { name: "Select Unit0 · CONTROLLER · Referenced by answer" }).className).toContain("arch-answer-reference"); expect(screen.queryByText("fake")).toBeNull(); });
