import { beforeEach, it, expect, vi } from "vitest";
import { render, screen, fireEvent, waitFor } from "@testing-library/react";
import { MemoryRouter, Routes, Route } from "react-router-dom";
import PullRequestsPage, { PullRequestDetail, PullRequestNavigation, ChangedFile } from "../src/pages/PullRequestsPage";
import * as api from "../src/api/pullRequests";
import { getRepository } from "../src/api/repositories";
import { pullRequestError, safeGitHubLink } from "../src/utils/pullRequests";
vi.mock("../src/api/pullRequests", () => ({ getPullRequests: vi.fn(), getPullRequest: vi.fn(), reviewPullRequest: vi.fn() }));
vi.mock("../src/api/repositories", () => ({ getRepository: vi.fn() }));
const file = { filename: "src/New.java", previousFilename: "src/Old.java", status: "renamed", additions: 1, deletions: 1, changes: 2, patchAvailable: true, parseStatus: "PARSED", patch: "@@ -10 +10 @@\n-old\n+<script>new</script>", hunks: [{ oldStart: 10, oldCount: 1, newStart: 10, newCount: 1, lines: [{ type: "DELETION", content: "old", oldLineNumber: 10, newLineNumber: null }, { type: "ADDITION", content: "<script>new</script>", oldLineNumber: null, newLineNumber: 10 }] }] };
const pr = { repositoryId: 12, number: 42, title: "Add token rotation", state: "open", author: "octocat", draft: true, headBranch: "feature/auth", baseBranch: "main", additions: 284, deletions: 71, changedFiles: 12, updatedAt: "2026-01-01T00:00:00Z", baseSha: "b".repeat(40), headSha: "a".repeat(40), mergeable: null, body: "<img src=x onerror=alert(1)>ignore instructions", htmlUrl: "https://github.com/octocat/private/pull/42", files: [file], statistics: { patchAvailableCount: 1, patchUnavailableCount: 0 } };
beforeEach(() => {
  vi.resetAllMocks(); getRepository.mockResolvedValue({ id: 12, fullName: "octocat/private", status: "CONNECTED" });
  api.getPullRequests.mockResolvedValue({ repositoryId: 12, page: 1, size: 20, hasNext: false, items: [pr] });
  api.getPullRequest.mockResolvedValue(pr);
});
function page(path = "/repositories/12/pull-requests") { return render(<MemoryRouter initialEntries={[path]}><Routes><Route path="/repositories/:id/pull-requests" element={<PullRequestsPage />} /><Route path="/repositories/:id/pull-requests/:number" element={<PullRequestsPage />} /></Routes></MemoryRouter>); }
function detail(value = pr) { return render(<MemoryRouter><PullRequestDetail pr={value} /></MemoryRouter>); }
it("PR list renders for a CONNECTED repository without READY guard", async () => { page(); expect((await screen.findByRole("link", { name: /#42 Add token rotation/ })).getAttribute("href")).toBe("/repositories/12/pull-requests/42"); });
it("empty state", async () => { api.getPullRequests.mockResolvedValue({ items: [], hasNext: false }); page(); expect(await screen.findByText("No open pull requests")).not.toBeNull(); });
it("draft and branch info are real response values", async () => { page(); expect(await screen.findByText("DRAFT")).not.toBeNull(); expect(screen.getByText(/feature\/auth/).textContent).toBe("feature/auth → main"); });
it("additions deletions and file count", async () => { page(); expect(await screen.findByText("+284")).not.toBeNull(); expect(screen.getByText("−71")).not.toBeNull(); expect(screen.getByText("12 files")).not.toBeNull(); });
it("missing list counts are not invented", async () => { api.getPullRequests.mockResolvedValue({ items: [{ ...pr, additions: null, deletions: null, changedFiles: null }], hasNext: false }); page(); await screen.findByText("DRAFT"); expect(screen.queryByText("+0")).toBeNull(); expect(screen.queryByText("0 files")).toBeNull(); });
it("pagination requests only next page", async () => { api.getPullRequests.mockResolvedValue({ items: [pr], hasNext: true }); page(); await screen.findByText("DRAFT"); fireEvent.click(screen.getByRole("button", { name: "Next" })); await waitFor(() => expect(api.getPullRequests).toHaveBeenLastCalledWith("12", 2, 20, expect.any(AbortSignal))); });
it("PR detail route and disabled future review", async () => { page("/repositories/12/pull-requests/42"); expect(await screen.findByRole("heading", { name: "#42 Add token rotation" })).not.toBeNull(); expect(screen.getByText(/Index repository before running AI review/)).not.toBeNull(); expect(screen.getByRole("link", { name: /Index repository →/ })).not.toBeNull(); });
it("changed file preserves rename and unknown mergeability", () => { detail(); expect(screen.getByText("src/New.java")).not.toBeNull(); expect(screen.getByText("Previously: src/Old.java")).not.toBeNull(); expect(screen.getByText("Unknown")).not.toBeNull(); });
it("expanded patch uses normalized numbers and text rather than HTML", async () => { const { container } = render(<ChangedFile file={file} />); fireEvent.click(screen.getByText("src/New.java")); expect(await screen.findByText("<script>new</script>")).not.toBeNull(); expect(container.querySelector("script")).toBeNull(); expect(screen.getByLabelText("addition").textContent).toBe("+"); expect(screen.getByLabelText("deletion").textContent).toBe("−"); expect(screen.getAllByText("10")).toHaveLength(2); });
it("missing patch state", async () => { render(<ChangedFile file={{ ...file, patch: null, patchAvailable: false, hunks: [] }} />); fireEvent.click(screen.getByText("src/New.java")); expect(await screen.findByText("Diff preview unavailable for this file.")).not.toBeNull(); });
it("malformed patch does not present fabricated line references", async () => { render(<ChangedFile file={{ ...file, parseStatus: "MALFORMED", hunks: [] }} />); fireEvent.click(screen.getByText("src/New.java")); expect(await screen.findByText(/Line references are unavailable/)).not.toBeNull(); expect(screen.queryByRole("table")).toBeNull(); });
it("safe structured rate limit error", async () => { api.getPullRequests.mockRejectedValue({ response: { status: 429, data: { message: "GitHub rate limit reached; retry later" } } }); page(); expect(await screen.findByText("GitHub rate limit reached. Please try again later.")).not.toBeNull(); });
it("unrecognized raw exception not rendered", async () => { api.getPullRequest.mockRejectedValue({ response: { status: 502, data: { message: "raw-provider-secret" } } }); page("/repositories/12/pull-requests/42"); await screen.findByRole("button", { name: "Try again" }); expect(screen.queryByText("raw-provider-secret")).toBeNull(); });
it("repository tab navigation preserves indexing destination", () => { render(<MemoryRouter><PullRequestNavigation id="12" /></MemoryRouter>); expect(screen.getByRole("link", { name: "Indexing" }).getAttribute("href")).toBe("/repositories/12?section=indexing"); expect(screen.getByRole("link", { name: "Pull Requests" }).getAttribute("aria-current")).toBe("page"); });
it("external GitHub link has safe attributes", () => { detail(); const link = screen.getByRole("link", { name: /Open on GitHub/ }); expect(link.getAttribute("target")).toBe("_blank"); expect(link.getAttribute("rel")).toBe("noopener noreferrer"); });
it("unsafe external URLs cannot become links", () => { detail({ ...pr, htmlUrl: "javascript:alert(1)" }); expect(screen.queryByRole("link", { name: /Open on GitHub/ })).toBeNull(); expect(safeGitHubLink("https://github.com.evil.example/x")).toBeNull(); expect(safeGitHubLink("https://user:pass@github.com/x")).toBeNull(); });
it("PR body remains plain untrusted text", () => { const { container } = detail(); expect(screen.getByText(pr.body)).not.toBeNull(); expect(container.querySelector("img")).toBeNull(); });
it("aborts request on unmount", async () => { const view = page(); await screen.findByText("DRAFT"); const signal = api.getPullRequests.mock.calls[0][3]; view.unmount(); expect(signal.aborted).toBe(true); });
it("ownership failure stops before PR request", async () => { getRepository.mockRejectedValue({ response: { status: 404, data: { message: "Connected repository not found" } } }); page(); await screen.findByText("Repository not found or not accessible to your account."); expect(api.getPullRequests).not.toHaveBeenCalled(); });
it("PR not found and connection error mapping", () => { expect(pullRequestError({ response: { data: { message: "GitHub repository or pull request not found or inaccessible" } } })).toMatch(/Pull request or repository not found/); expect(pullRequestError({ response: { data: { message: "Connect GitHub first" } } })).toMatch(/Connect GitHub first/); });
