CREATE TABLE repositories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    github_repository_id BIGINT NOT NULL,
    owner VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    full_name VARCHAR(511) NOT NULL,
    default_branch VARCHAR(255),
    private_repository BOOLEAN NOT NULL,
    html_url TEXT NOT NULL,
    primary_language VARCHAR(255),
    github_updated_at TIMESTAMPTZ,
    connected_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) NOT NULL DEFAULT 'CONNECTED'
        CHECK (status IN ('CONNECTED', 'INDEXING', 'READY', 'FAILED')),
    CONSTRAINT uk_repositories_user_github UNIQUE (user_id, github_repository_id)
);
