CREATE TABLE repository_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repository_id BIGINT NOT NULL REFERENCES repositories(id) ON DELETE CASCADE,
    path TEXT NOT NULL,
    file_name TEXT NOT NULL,
    language VARCHAR(40) NOT NULL,
    github_sha VARCHAR(64) NOT NULL,
    size_bytes BIGINT NOT NULL CHECK (size_bytes >= 0),
    content_hash VARCHAR(64) NOT NULL,
    line_count INTEGER NOT NULL CHECK (line_count >= 0),
    indexed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (repository_id, path),
    UNIQUE (id, repository_id)
);
