CREATE TABLE code_chunks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repository_file_id BIGINT NOT NULL,
    repository_id BIGINT NOT NULL REFERENCES repositories(id) ON DELETE CASCADE,
    chunk_index INTEGER NOT NULL CHECK (chunk_index >= 0),
    content TEXT NOT NULL,
    start_line INTEGER NOT NULL CHECK (start_line >= 1),
    end_line INTEGER NOT NULL CHECK (end_line >= start_line),
    symbol_name TEXT,
    symbol_type VARCHAR(40),
    content_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (repository_file_id, repository_id) REFERENCES repository_files(id, repository_id) ON DELETE CASCADE,
    UNIQUE (repository_file_id, chunk_index)
);
CREATE INDEX idx_code_chunks_repository ON code_chunks(repository_id);
CREATE INDEX idx_code_chunks_file ON code_chunks(repository_file_id);
CREATE INDEX idx_code_chunks_hash ON code_chunks(content_hash);
