CREATE TABLE indexing_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repository_id BIGINT NOT NULL REFERENCES repositories(id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL CHECK (status IN ('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    heartbeat_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    source_commit VARCHAR(64),
    files_discovered INTEGER NOT NULL DEFAULT 0,
    files_indexed INTEGER NOT NULL DEFAULT 0,
    files_skipped INTEGER NOT NULL DEFAULT 0,
    chunks_created INTEGER NOT NULL DEFAULT 0,
    line_count BIGINT NOT NULL DEFAULT 0,
    languages JSONB NOT NULL DEFAULT '{}',
    skip_reasons JSONB NOT NULL DEFAULT '{}',
    error_message TEXT
);
CREATE UNIQUE INDEX uk_indexing_jobs_active ON indexing_jobs(repository_id) WHERE status IN ('QUEUED', 'RUNNING');
CREATE INDEX idx_indexing_jobs_repository ON indexing_jobs(repository_id, id DESC);

-- Bounded, per-file staging. Live index remains unchanged until atomic publication.
CREATE TABLE indexing_staged_files (
    job_id BIGINT NOT NULL REFERENCES indexing_jobs(id) ON DELETE CASCADE,
    path TEXT NOT NULL,
    file_name TEXT NOT NULL,
    language VARCHAR(40) NOT NULL,
    github_sha VARCHAR(64) NOT NULL,
    size_bytes BIGINT NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    line_count INTEGER NOT NULL,
    chunks JSONB NOT NULL,
    PRIMARY KEY (job_id, path)
);
