ALTER TABLE code_chunks ADD CONSTRAINT uk_code_chunks_id_repository UNIQUE (id, repository_id);
CREATE TABLE chunk_embeddings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_chunk_id BIGINT NOT NULL UNIQUE,
    repository_id BIGINT NOT NULL REFERENCES repositories(id) ON DELETE CASCADE,
    embedding VECTOR(1536) NOT NULL CHECK (vector_norm(embedding) > 0),
    provider VARCHAR(512) NOT NULL,
    model VARCHAR(255) NOT NULL,
    dimensions INTEGER NOT NULL CHECK (dimensions = 1536),
    content_hash VARCHAR(64) NOT NULL,
    input_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (code_chunk_id, repository_id) REFERENCES code_chunks(id, repository_id) ON DELETE CASCADE
);
CREATE INDEX idx_chunk_embeddings_repository ON chunk_embeddings(repository_id);
CREATE INDEX idx_chunk_embeddings_content_hash ON chunk_embeddings(content_hash);
CREATE INDEX idx_chunk_embeddings_reuse ON chunk_embeddings(repository_id, provider, model, input_hash);
CREATE INDEX idx_chunk_embeddings_cosine ON chunk_embeddings USING hnsw (embedding vector_cosine_ops);

CREATE TABLE indexing_staged_embeddings (
    job_id BIGINT NOT NULL,
    path TEXT NOT NULL,
    chunk_index INTEGER NOT NULL,
    embedding VECTOR(1536) NOT NULL CHECK (vector_norm(embedding) > 0),
    provider VARCHAR(512) NOT NULL,
    model VARCHAR(255) NOT NULL,
    dimensions INTEGER NOT NULL CHECK (dimensions = 1536),
    content_hash VARCHAR(64) NOT NULL,
    input_hash VARCHAR(64) NOT NULL,
    PRIMARY KEY (job_id, path, chunk_index),
    FOREIGN KEY (job_id, path) REFERENCES indexing_staged_files(job_id, path) ON DELETE CASCADE
);
ALTER TABLE indexing_jobs ADD COLUMN embeddings_created INTEGER NOT NULL DEFAULT 0;
ALTER TABLE indexing_jobs ADD COLUMN embeddings_reused INTEGER NOT NULL DEFAULT 0;
ALTER TABLE indexing_jobs ADD COLUMN embedding_model VARCHAR(255);
